version: '3.8'

volumes:
  postgres-volume:

services:
  app:
    container_name: ${PROJECT_NAME}-app
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    ports:
      - 5173:5173
    depends_on:
      - db
    volumes:
      - ./src/:/var/www/html
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

  web:
    container_name: ${PROJECT_NAME}-web
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - ${WEB_PORT}:80
    depends_on:
      - app
    volumes:
      - ./src/:/var/www/html

  db:
    container_name: ${PROJECT_NAME}-db
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGTZ: 'Asia/Tokyo'
    volumes:
      - postgres-volume:/var/lib/postgresql